on:
  workflow_call:
    outputs:
      name:
        description: "The conan package name"
        value: ${{ jobs.get_conan_package_info.outputs.name }}
        
env:
  REPOSITORY_NAME: $(basename ${{ github.repository }})
        
jobs:
  get_conan_package_info:
    runs-on: ubuntu-latest
    outputs: 
      package_name: ${{steps.get_name.outputs.name}}
    steps:
      - name: Get name
        id: get_name
        run: |
          name="platform.$(echo ${{env.REPOSITORY_NAME}} | tr '[:upper:]' '[:lower:]')"
          echo "name=${package_name}" >> $GITHUB_OUTPUT
