on:
  workflow_call:
    outputs:
      name:
        description: "The conan package name"
        value: ${{ jobs.get_conan_package_info.outputs.name }}
        
jobs:
  get_conan_package_info:
    runs-on: ubuntu-latest
    outputs: 
      name: ${{ steps.set_name.outputs.name }}
    steps:
      - name: Set name
        id: set_name
        run: echo "::set-output name=name::platform.${{ github.event.repository.name | lower }}"
