on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        
jobs:
  push_to_conan:
    if: startsWith(github.ref, 'refs/tags/cpp_')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Publish to the official conan repository
        uses: Minimonium/conan-request-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packageName: ${{inputs.name}}
      - name: Publish to the linksplatform conan repository
        uses: Minimonium/conan-request-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packageName: ${{inputs.name}}
          upstreamOwner: 'linksplatform'
